//Provides attributes for model validation such as [Required] and [EmailAddress]
using System.ComponentModel.DataAnnotations;

//Namespace groups domain models
namespace AccessibleBank.Models
{
    //Represents an application user or customer in the banking system
    public class User
    {
        //Primary key for the user entity, automatically generated by the database
        public int Id { get; set; }

        //User's email address, used for login and communication
        //Decorated with [Required] to enforce that a name must be provided
        //Defined as a nullable string to satisfy nullable reference type rules, but validation ensures it's not null at runtime
        [Required]
        public string? Name { get; set; }

        //User's email address, used for login and communication
        //Decorated wit [Required] to enforce presence, and [EmailAddress] to validate proper email format
        //Nullable string type for code safety, but validation enforces a non-null email.
        [Required, EmailAddress]
        public string? Email { get; set; }

        //Stores the user's password hash after registration
        //Decorated with [Required] to enforce that a password must be provided
        //Nullable string type, though in practice registration logic hashes and stores a non-null value
        //Hashing occurs before saving to the database
        [Required]
        public string? Password { get; set; }
    }
}
